### ISSUE TITLE
Access

### ISSUE THREAD

**Issue by amr08** [variadicjs/variadicjs.github.io#1]
Hi @jhowardjr -  I am receiving this error while pushing a branch.  (I cloned it)  Do I need to be invited into this specific repo?

![screen shot 2018-01-27 at 2 59 54 pm](https://user-images.githubusercontent.com/17239196/35475793-c1ce45c0-0372-11e8-8777-e5c7be39617b.png)

**Comment by jhowardjr** [comment]
@amr08 sorry about that. I changed the default privileges from read to write. Give it try and let me know.

**Comment by amr08** [comment]
@jhowardjr Well I got further, but still getting this:

![screen shot 2018-01-27 at 10 39 52 pm](https://user-images.githubusercontent.com/17239196/35478723-1e19e236-03b3-11e8-8aa4-7d38a9add4f0.png)

I double checked my password.  Wondering if it wants the variadicjs username and password

**Comment by jhowardjr** [comment]
Hmmm. It should be your GitHub account information. I actually use ssh so I don't have to enter my username and password. https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account. Once you do that you can change your origin to use ssh by doing the following:

**Comment by amr08** [comment]
@jhowardjr Yea I use ssh too and can push to my own repos.  Checked the remote and it's there: 
 
![screen shot 2018-01-27 at 11 22 53 pm](https://user-images.githubusercontent.com/17239196/35478975-141390ec-03b9-11e8-966d-37b47f14c432.png)

I'll have to do some googling to see if anyone else has had trouble with this.

**Comment by amr08** [comment]
@jhowardjr 

For anyone else, it's an https issue apparently with github pages.  I was able to bypass by generating an access token - steps here:

https://mycyberuniverse.com/web/how-fix-fatal-authentication-failed-for-https-github-com.html
