### ISSUE TITLE
Redesign input form to to accept variable number of params

### ISSUE THREAD

**Issue by mradenovic** [variadicjs/variadicjs.github.io#16]
Most of the functions throw an error or return the wrong result if not all three params are provided. Negative numbers and decimals can't be used.

Redesign the input form to allow a variable number of both positive and negative decimal numbers.

**Comment by amr08** [comment]
This can be done by adjusting the regex.

**Comment by mradenovic** [comment]
Solved with PR #19. If it needs further improvements, please open a new issue.
