### ISSUE TITLE
Refactor code for easier maintenance

### ISSUE THREAD

**Issue by mradenovic** [variadicjs/variadicjs.github.io#17]
In order to add testing to dev process, and to be able to share the work, we need to take Divide and conquer approach :smile: .

**Comment by jhowardjr** [comment]
I'll get up to speed with Jest. What component were you going to start with? I'll pick out whatever it left.

**Comment by mradenovic** [comment]
I was thinking to split code into App, CardLIst, Card, InputComponent, ResultOutput, CodeOutput, not necessarily named like that. Then we can work on components separately. I have already added #18 for basic testing.

**Comment by mradenovic** [comment]
I've created  new `extract-components` branch as an example. It is still work in progress, but FuncCode component is already extracted and can be improved separately.

**Comment by mradenovic** [comment]
Solved with PR #19. If it needs further improvements, please open a new issue.
