### ISSUE TITLE
Pull in the avatar for the user responsible for the function.

### ISSUE THREAD

**Issue by jhowardjr** [variadicjs/variadicjs.github.io#20]
Pull in the avatar for the user responsible for the function.

**Comment by jhowardjr** [comment]
FYI. Adding .png to the end of the github users url redirect to the gravatar. For example, https://github.com/jhowardjr.png redirects to https://avatars1.githubusercontent.com/u/1757435?v=4

**Comment by mradenovic** [comment]
How do we get the user responsible for the function?

**Comment by jhowardjr** [comment]
We can extract the author from jsDoc. I’m working on adding the documentation on the package side.

**Comment by jhowardjr** [comment]
variadic.js @ v0.0.23 should have the @author field in the jsDoc for each function.
