### ISSUE TITLE
Display the code for each function in a modal dialog

### ISSUE THREAD

**Issue by mradenovic** [variadicjs/variadicjs.github.io#22]
![image](https://user-images.githubusercontent.com/10821730/36272550-db9ea486-124f-11e8-9113-6b8554d74f61.png)
The original idea to display the code on the back of the card is possible. However, code display size is variable and the card size shouldn't be. The current solution is also a bit awkward. Should we display the code in a modal window instead, possibly full screen?

**Comment by jhowardjr** [comment]
I think the full screen would look good. Modal windows work too.

**Comment by mradenovic** [comment]
This decision closes #6 and #7.

**Comment by mradenovic** [comment]
Wrong reference #24 instead of #22 addressed in #25.
