### ISSUE TITLE
How to display cards for user

### ISSUE THREAD

**Issue by amr08** [variadicjs/variadicjs.github.io#30]
@jhowardjr @mradenovic Was just playing around with ideas other than displaying them in rows.   I came up with something like this.  It is also swipeable on mobile:
![swipescroll](https://user-images.githubusercontent.com/17239196/36358953-0fcb9494-14e4-11e8-9622-c1b53f561c43.gif)

One thing to think about with this approach is that we don't yet have a way of displaying a specific card if someone is requesting it. Which in this case, would require some additional logic to put the requested function in "the front" [0] of the list. Otherwise, they can scroll through.   Anyway, let me know your thoughts and if you would like me to pursue this further!

**Comment by jhowardjr** [comment]
Cool! I like it, especially for mobile. Could do like a in page search that auto suggest functions as you type. Once you click on one it could then scroll to the desired function.

**Comment by mradenovic** [comment]
I like it too. We could probably add a list of functions to the menu.
