### ISSUE TITLE
Prevent "e's" from being entered

### ISSUE THREAD

**Issue by amr08** [variadicjs/variadicjs.github.io#37]
Strange, but the letter "e" is getting through in the inputs.

**Comment by mradenovic** [comment]
Input is of type `number`. It allows [E-notation](https://en.wikipedia.org/wiki/Scientific_notation#E-notation). **1e3** will be accepted as **1x10<sup>3</sup>**.

**Comment by amr08** [comment]
Wow would have never guessed that. 😄   Closing
