### ISSUE TITLE
Looks a bit off center on mobile

### ISSUE THREAD

**Issue by jhowardjr** [variadicjs/variadicjs.github.io#39]
We'll need to look at the styling on different screen sizes. 

![img_0991](https://user-images.githubusercontent.com/1757435/36636300-18bfac4a-1992-11e8-9a1d-780b186e88d6.PNG)

**Comment by amr08** [comment]
Addressed in PR #47

**Comment by amr08** [comment]
Being picky, but now that everything else is centered the input looks a little off as I look at it.  Maybe just extending the width will do it natually.  Easy fix for whoever can get to it first in the next PR.
