### ISSUE TITLE
Revert to Avatar

### ISSUE THREAD

**Issue by amr08** [variadicjs/variadicjs.github.io#40]
@jhowardjr @mradenovic Can we revert to the previous commit Avatar See: https://github.com/variadicjs/variadicjs.github.io/pull/36/commits/a3f17b2db7b90835af16f99224b8cc81724b301b.  I created a reusable Avatar component with the goal of using it again for the logo in navbar.  I originally customized it for the authors, but realized Avatar could be used more globally.  Making a custom author component is not very dry (what I originally did before I refactored my own code)

**Comment by jhowardjr** [comment]
@amr08 I just recovered the avatar component on the recover-avatar branch.

**Comment by amr08** [comment]
@jhowardjr Sounds good! @mradenovic  The styling to center the avatar in the cards will be pretty easy to apply, but feel free to move in your code and test code (just keep Avatar around to use for both the author pictures and the future logo in navbar)

**Comment by mradenovic** [comment]
I should have used Avatar in Author. I'll look into it. For now, I added tests for Avatar in PR #41.
