### ISSUE TITLE
Input field doesn't show errors anymore

### ISSUE THREAD

**Issue by mradenovic** [variadicjs/variadicjs.github.io#44]
Before we switched to react-materialize, input field was showing function error if any on run. Now, the field indicates that there was an error, but it does not display it.

**Comment by amr08** [comment]
hmm I can't seem to see any indication that there is an error in the fields other than the html5 warning. What is a way I can trigger one?

**Comment by mradenovic** [comment]
Run `sum` with no params. It will throw `Must provide one or more parameters` and the bottom border of the input field will turn red. Error message should show up under but it does not.

Error message is set in `handleRunCode` and passed down to FuncParams. It looks like materialize Input does not pass the message properly.

```js
// FuncCard.js

  handleRunCode(e) {
    let params = this.state.params;
    try {
      let result = this.props.func(...params);
      this.setState({result: result, error: ''});
    }
    catch(err) {
      this.setState({result: '', error: err.message})
    }
  }
```
