### ISSUE TITLE
Shout out to us?

### ISSUE THREAD

**Issue by amr08** [variadicjs/variadicjs.github.io#46]
We have the authors of variadic, but wondering if there is a way to give credit to the website creators in somewhere as well. 🙂   Any ideas? Is there a UX best practice for something like that?

**Comment by jhowardjr** [comment]
Usually the footer, but don’t see why it couldn’t be somewhere else.

**Comment by khusbuchandra** [comment]
I was just lurking around and saw the the demo website and it looks great 👌, didn't know so much work was going on here. Definitely the creators should get the credit 👍

**Comment by amr08** [comment]
haha hey @khusbuchandra!  Thanks so much! We had a good little system - really enjoyed the process 🙂  A few more tweaks here and there and we should be good to go I think!

**Comment by jhowardjr** [comment]
Could do like a welcome card as the first card to display that lists all the participants.

**Comment by amr08** [comment]
@jhowardjr Yea that might be be cool - it could give a brief explanation of the demo with a link back to variadic, and contributors to demo site. Are you thinking this data come from variadic? Or would we create it in here and unshift it to beginning of the array

**Comment by jhowardjr** [comment]
Adding it to the array on the demo side sounds like a plan to me. Been off
and on lately, because I'm working on purchasing a house.

**Comment by mradenovic** [comment]
+1 adding to the array :)

**Comment by jhowardjr** [comment]
@amr08 this should be live now. BTW would you be interested in taking over the repo? I can transfer the organization to you if you are interested.

**Comment by amr08** [comment]
@jhowardjr Looks good - Maybe? I'm kinda nervous. A few questions:
-Would it be just this repo?  
-Is there anything I should take into consideration?
-What are the steps you are taking to deploy to github pages in the master branch (move everything manually or by the `npm run deploy`?)
