### ISSUE TITLE
How do we envision displaying the output within the cards?

### ISSUE THREAD

**Issue by jhowardjr** [variadicjs/variadicjs.github.io#5]
How, do we envision displaying the results from each function? Imagine each card representing a function.

**Comment by amr08** [comment]
@jhowardjr if you post on the slack channel again (or on the forums) that we have a fresh react app that needs some building out, I bet we'll get more takers.  I'm interested to see what others come up with!

**Comment by jhowardjr** [comment]
<img width="1415" alt="screen shot 2018-02-03 at 8 56 28 am" src="https://user-images.githubusercontent.com/1757435/35768183-d8e3b2c4-08c5-11e8-91ba-cf396a02d726.png">

Something I quickly threw together.

**Comment by amr08** [comment]
@jhowardjr Awesome! - nice to see the concept come together.  Really looking forward to helping building this out!

**Comment by amr08** [comment]
@jhowardjr Would we want to use fields for the input so that the user could type and submit any numbers through?  Also, materialUI out of the box doesn't appear to have a flip, but they do have an "extendable" feature, where a user could click to "see code" and it could extend the card where we could "reveal" the code. http://www.material-ui.com/#/components/card

**Comment by amr08** [comment]
Yea true, it wouldn't be hard to implement some additional css to make it happen - I think the flip sounds pretty cool. At least we have the card extender as another option if we get stuck for some reason. Although, I am wondering about the drag and drop feature's utility.  I think inputs might be cleaner, but I see your goal of wanting to add in something interactive/different for the user. Hmm... Let's have @mradenovic weigh in as well!

**Comment by jhowardjr** [comment]
@amr08 we can start with input fields. I pushed a branch up called feature-demo-isEven. I'm new to react, but I set up a function called ```handleClick```, which essentially takes an array and execute the function respective to the card. So it would seem whatever the interface looks like as long as we get an array of values we can get something working. Let me know how I can help, been looking for a reason to try react.

**Comment by mradenovic** [comment]
I pushed new playground branch [`feat-demo-code`](/variadicjs/variadicjs.github.io/tree/feat-demo-code) to test dynamic code and expandable feature. However,  `npm run build` fails to minimize variadic.js (issue #11). No pull request until we solve this :smile:.

**Comment by amr08** [comment]
@jhowardjr I wouldn't have known you just tried it for the first time - good job. Were you going to do PR into develop?
