### ISSUE TITLE
I'd like to contribute `absoluteValue`

### ISSUE THREAD

**Issue by tdnelson2** [variadicjs/variadicjs.github.io#53]
I'm in the GWG Scholarship Challenge and would like to contribute to this project! I understand one of the things yet to be completed is a function returning the absolute value of each number (i.e. their positive value). Here's a snippet of what I wrote:

```
exports.absoluteValue = (...params) => {
  handleErrors(params);
  return params.map((num) => Math.abs(num));
}
```

Is this what you're looking for? If so, can I pull request it to you?

**Comment by mradenovic** [comment]
Welcome, @tdnelson2! This project is based on [variadic.js](https://github.com/variadicjs/variadic.js) project. If you want to contribute new function, check how other functions are done and make a PR there. Make sure to add jsDoc :smile:

**Comment by amr08** [comment]
Closing as issue is for the [variadic library repo](https://github.com/variadicjs/variadic.js)
