### ISSUE TITLE
Remove build files from develop branch

### ISSUE THREAD

**Issue by mradenovic** [variadicjs/variadicjs.github.io#9]
It looks like everything from the `build` folder is also in the root of the `develop` branch. Should we remove those files to make the branch clear of unnecessary code?

**Comment by jhowardjr** [comment]
It looks like the build directory is in the .gitignore file so it shouldn't be in the repo.

**Comment by amr08** [comment]
@jhowardjr  I believe it's ./build/static/... so it is in the develop branch.  Really weird I wonder why .gitignore wouldn't cover the static folder.  Maybe one of us committed before updating the .gitignore.

**Comment by amr08** [comment]
I added the remove to my PR for the typo
